dist: trusty

sudo: false

language: php

php:
  - 7.3.5

matrix:
  fast_finish: true

install: true

before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer require phpunit/phpunit

script:
  - vendor/bin/phpunit tests/ --coverage-html build/ --testdox

branches:
  only:
    - master